name: Run Scraper
on:
  push:
    branches:
      - main
    
  # schedule:
  #     - cron: '*/5 * * * *'  # Cada 5 minutos

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        env:
            TELEGRAM_API_TOKEN: ${{ vars.TELEGRAM_API_TOKEN }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt

            - name: Install cron daemon
              run: |
                sudo apt-get update
                sudo apt-get install cron -y
                sudo service cron start

            - name: Set up cronjob
              run: |
                echo "*/5 * * * * python main.py" | sudo tee -a /etc/cron.d/scraper-cron

            - name: Debug environment
              run: env
                
            - name: Run scraper
              run: python main.py

