name: Run Scraper
on:
  push:
    branches:
      - main
    
  schedule:
      - cron: '0,30 * * * *'

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          id-token: write
        env:
            TZ: America/Argentina/Buenos_Aires # Cambia a la zona horaria deseada
            TELEGRAM_API_TOKEN: ${{ vars.TELEGRAM_API_TOKEN }}
            TELEGRAM_CHAT_IDS: ${{ vars.TELEGRAM_CHAT_IDS }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                
            - name: Run scraper
              run: python main.py

