name: Run Scraper
on:
  push:
    branches:
      - main
    
  schedule:
      - cron: '*/5 * * * *'  # Cada 5 minutos
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: 3.12.6
            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
         
            - name: Run scraper
              env:
                TELEGRAM_API_TOKEN: ${{ vars.TELEGRAM_API_TOKEN }}   
              run: python main.py
            - name: PrintVar
              run: echo "var ${{ vars.TELEGRAM_API_TOKEN }}"
