name: Clean Old Runs

on:
  push:
    branches:
        - main
  schedule:
    - cron: "0 0 * * *"  # Ejecuta esta acción diariamente a medianoche

jobs:
  clean-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete Old Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Lista los workflows específicos
          workflows=("Clean Old Runs" "Run Scraper")

          for workflow in "${workflows[@]}"; do
            echo "Processing workflow: $workflow"

            # Lista los últimos 100 runs y excluye los últimos 3
            runs_to_delete=$(gh run list --workflow "$workflow" --status completed --limit 100 --json databaseId | jq -r '.[3:] | .[].databaseId')

            if [ -z "$runs_to_delete" ]; then
              echo "No runs to delete for $workflow"
              continue
            fi

            for run_id in $runs_to_delete; do
              echo "Deleting run ID: $run_id"
              # Elimina directamente el run usando su ID
              gh run delete "$run_id" --yes
            done
          done
