name: Clean Old Runs

on:
    workflow_run:
        workflows:
          - Run Scraper
        types:
          - completed

jobs:
  clean-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete Old Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Lista los workflows específicos
          workflows=("Clean Old Runs" "Run Scraper")

          for workflow in "${workflows[@]}"; do
            echo "Processing workflow: $workflow"

            # Lista los últimos 100 runs y excluye los últimos 3
            runs_to_delete=$(gh run list --workflow "$workflow" --status completed --limit 100 --json databaseId | jq -r '.[3:] | .[].databaseId')

            if [ -z "$runs_to_delete" ]; then
              echo "No runs to delete for $workflow"
              continue
            fi

            for run_id in $runs_to_delete; do
              echo "Deleting run ID: $run_id"
              # Usa 'yes' para confirmar automáticamente
              yes | gh run delete "$run_id"
            done
          done
