name: Clean Old Runs

on:
  push:
    branches:
        - main
  schedule:
    - cron: "0 0 * * *"  # Ejecuta esta acción diariamente a medianoche

jobs:
  clean-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Delete Old Runs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Lista todos los workflows
          workflows=$(gh workflow list --json name --jq '.[].name')

          for workflow in $workflows; do
            echo "Processing workflow: $workflow"

            # Obtener los IDs de los runs a eliminar, dejando los últimos 3
            runs_to_delete=$(gh run list --workflow "$workflow" --status completed --limit 100 --json databaseId | jq -r '.[3:] | .[].databaseId')

            for run_id in $runs_to_delete; do
              echo "Deleting run ID: $run_id"
              gh run delete --id "$run_id" --yes
            done
          done
